// <auto-generated />
using System;
using ApartmentRentalSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApartmentRentalSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApartmentRentalDbContext))]
    [Migration("20200926121953_InitialDomainTables")]
    partial class InitialDomainTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApartmentRentalSystem.Domain.Models.ApartmentAds.ApartmentAd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BrokerId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Floor")
                        .HasColumnType("int")
                        .HasMaxLength(50);

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(2048)")
                        .HasMaxLength(2048);

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("NeighborhoodId")
                        .HasColumnType("int");

                    b.Property<decimal>("pricePerMonth")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BrokerId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("NeighborhoodId");

                    b.ToTable("ApartmentAds");
                });

            modelBuilder.Entity("ApartmentRentalSystem.Domain.Models.ApartmentAds.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasMaxLength(1000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("ApartmentRentalSystem.Domain.Models.ApartmentAds.Neighborhood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Neighborhoods");
                });

            modelBuilder.Entity("ApartmentRentalSystem.Domain.Models.Brokers.Broker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Brokers");
                });

            modelBuilder.Entity("ApartmentRentalSystem.Domain.Models.ApartmentAds.ApartmentAd", b =>
                {
                    b.HasOne("ApartmentRentalSystem.Domain.Models.Brokers.Broker", null)
                        .WithMany("ApartmentAds")
                        .HasForeignKey("BrokerId");

                    b.HasOne("ApartmentRentalSystem.Domain.Models.ApartmentAds.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApartmentRentalSystem.Domain.Models.ApartmentAds.Neighborhood", "Neighborhood")
                        .WithMany()
                        .HasForeignKey("NeighborhoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("ApartmentRentalSystem.Domain.Models.ApartmentAds.Options", "Options", b1 =>
                        {
                            b1.Property<int>("ApartmentAdId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<bool>("HasBasement")
                                .HasColumnType("bit");

                            b1.Property<bool>("HasParking")
                                .HasColumnType("bit");

                            b1.HasKey("ApartmentAdId");

                            b1.ToTable("ApartmentAds");

                            b1.WithOwner()
                                .HasForeignKey("ApartmentAdId");

                            b1.OwnsOne("ApartmentRentalSystem.Domain.Models.ApartmentAds.HheatingType", "HheatingType", b2 =>
                                {
                                    b2.Property<int>("OptionsApartmentAdId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int")
                                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                                    b2.Property<int>("Value")
                                        .HasColumnType("int");

                                    b2.HasKey("OptionsApartmentAdId");

                                    b2.ToTable("ApartmentAds");

                                    b2.WithOwner()
                                        .HasForeignKey("OptionsApartmentAdId");
                                });
                        });
                });

            modelBuilder.Entity("ApartmentRentalSystem.Domain.Models.Brokers.Broker", b =>
                {
                    b.OwnsOne("ApartmentRentalSystem.Domain.Models.Brokers.PhoneNumber", "PhoneNumber", b1 =>
                        {
                            b1.Property<int>("BrokerId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("BrokerId");

                            b1.ToTable("Brokers");

                            b1.WithOwner()
                                .HasForeignKey("BrokerId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
